### ISSUE TITLE
/instance/agent when updating configuration (resource) HTTP Error code 422

### ISSUE THREAD

**Issue by pszynk** [guard-project/cb-manager#4]
Very similar to #3

Request to: 
```
PUT http://guard3.westeurope.cloudapp.azure.com:5000/instance/agent/pgafilter@backend-prod
```

with content:

```javascript
{
    "id": "pgafilter@backend-prod",
    "operations": {
        "resources": [
            {
            "content": "some text",
            "id": "rule-file"
            }
        ]
    }
}
```

gets a response:

```js
[
  {
    "code": 422,
    "error": true,
    "lcp_response": [
      {
        "code": 422,
        "error": true,
        "exception": {
          "filename": "/opt/cb-manager/resource/agent/handler/lcp.py",
          "line": 81,
          "reason": "{'resources': [ValidationException({'path': [ValidationException('Value required for this field.')], 'content': [ValidationException('Value required for this field.')]})]}"
        },
        "message": "Response from LCP(backend-prod@35.193.65.139:4000) not valid",
        "status": "Unprocessable Entity"
      }
    ],
    "message": "Not possible to update a agent instance with the id=pgafilter@backend-prod",
    "status": "Unprocessable Entity"
  }
]
```

*BUT* the configuration file gets updated. Maybe this line is a problem?

https://github.com/guard-project/cb-manager/blob/7386d38242e0e02bbfd5f546fc443dd313720047/document/agent/catalog.py#L44

**Comment by alexcarrega** [comment]
The issue should be solved.

### Example

**PUT** _instance/agent_ **HTTP/1.1**
```json
{
    "id": "filebeat@user-vm",
    "operations": {
        "resources": [
            {
                "id": "config-file",
                "content": "test"
            }
        ]
    }
}
```

Result:

```http
HTTP/1.1 200 OK
Connection: close
Content-Length: 395
Content-Type: application/json
Date: Tue, 16 Mar 2021 21:54:47 GMT
Server: GUARD - Context Broker Manager v:1.0.3
```

```json
[
  {
    "code": 200,
    "error": false,
    "lcp_response": [
      {
        "code": 200,
        "content": "test2",
        "data": {
          "content": "test2",
          "path": "/opt/filebeat/config/log.yml"
        },
        "error": false,
        "id": "config-file",
        "path": "/opt/filebeat/config/log.yml",
        "status": "OK",
        "timestamp": "2021/03/16T21:54:48",
        "type": "resource"
      }
    ],
    "message": "Agent instance with the id=filebeat@user-vm correctly updated",
    "status": "OK"
  }
]
```

**Comment by alexcarrega** [comment]
> Very similar to #3
> 
> Request to:
> 
> ```
> PUT http://guard3.westeurope.cloudapp.azure.com:5000/instance/agent/pgafilter@backend-prod
> ```
> 
> with content:
> 
> ```js
> {
>     "id": "pgafilter@backend-prod",
>     "operations": {
>         "resources": [
>             {
>             "content": "some text",
>             "id": "rule-file"
>             }
>         ]
>     }
> }
> ```
> 
> gets a response:
> 
> ```js
> [
>   {
>     "code": 422,
>     "error": true,
>     "lcp_response": [
>       {
>         "code": 422,
>         "error": true,
>         "exception": {
>           "filename": "/opt/cb-manager/resource/agent/handler/lcp.py",
>           "line": 81,
>           "reason": "{'resources': [ValidationException({'path': [ValidationException('Value required for this field.')], 'content': [ValidationException('Value required for this field.')]})]}"
>         },
>         "message": "Response from LCP(backend-prod@35.193.65.139:4000) not valid",
>         "status": "Unprocessable Entity"
>       }
>     ],
>     "message": "Not possible to update a agent instance with the id=pgafilter@backend-prod",
>     "status": "Unprocessable Entity"
>   }
> ]
> ```
> 
> _BUT_ the configuration file gets updated. Maybe this line is a problem?
> 
> https://github.com/guard-project/cb-manager/blob/7386d38242e0e02bbfd5f546fc443dd313720047/document/agent/catalog.py#L44

You have to use the last version of LCP.
